# Generated by Django 4.0.5 on 2022-09-08 10:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='TestCRUD',
        ),
        migrations.RemoveField(
            model_name='colour',
            name='hex',
        ),
        migrations.AddField(
            model_name='colour',
            name='hex_log',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=7), default=['tmp'], size=10),
            preserve_default=False,
        ),
    ]
