# Generated by Django 4.0.5 on 2022-06-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='bio',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
