# Generated by Django 4.0.5 on 2022-09-08 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_device_delete_testcrud_remove_colour_hex_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='colour',
            new_name='colour_tmp',
        ),
        migrations.RemoveField(
            model_name='colour',
            name='name',
        ),
        migrations.AddField(
            model_name='colour',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.portfolio'),
        ),
    ]
