# Generated by Django 4.0.5 on 2022-09-09 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_colourhistory_user_delete_colour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IpCounter',
        ),
        migrations.AlterField(
            model_name='user',
            name='history_colour_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.colourhistory'),
        ),
    ]
