# Generated by Django 4.0.5 on 2022-06-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='created',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='linenos',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
