# Generated by Django 4.0.5 on 2022-09-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_ipcounter_alter_user_history_colour_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='portfolio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
