# Generated by Django 4.0.5 on 2022-09-10 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_portfolio_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='colour_tmp',
            new_name='colour',
        ),
    ]
