# Generated by Django 4.0.5 on 2022-07-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_id',
        ),
    ]
