# Generated by Django 4.0.5 on 2022-08-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_device_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
        migrations.AddField(
            model_name='device',
            name='type_id',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='consumption',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='data_id',
            field=models.PositiveIntegerField(),
        ),
    ]
