# Generated by Django 4.0.5 on 2022-08-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSRF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200)),
                ('synchronizer_token', models.CharField(max_length=2000)),
                ('encrypted_token', models.CharField(max_length=2000)),
                ('double_submitted_cookie', models.CharField(max_length=2000)),
            ],
        ),
    ]
