# Generated by Django 4.0.5 on 2022-08-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_csrf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csrf',
            name='double_submitted_cookie',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='csrf',
            name='encrypted_token',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='csrf',
            name='synchronizer_token',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
