# Generated by Django 4.0.5 on 2022-08-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_csrf_double_submitted_cookie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csrf',
            name='ip',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
