# Generated by Django 4.0.5 on 2022-08-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='location',
            name='username',
            field=models.CharField(default='ffff', max_length=200),
            preserve_default=False,
        ),
    ]
