version: "3.9"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=ps
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=beyond
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    image: beyond
    build: ./django-docker/
    command: ./run_django.sh
    depends_on:
      - db
    ports:
      - "8000:8000"
volumes:
  postgres_data: 
