---
$schema: 'http://json-schema.org/draft-07/schema#'
id: 'flexopt://backend_responses/algorithm_response.yaml#'
title: Algorithm response
description: Algorithm response configuration schema
type: object
oneOf:
  - '$ref': '#/definitions/success'
  - '$ref': '#/definitions/fail'
definitions:
  success:
    type: object
    required:
      - type
      - status
      - offers
    properties:
      type:
        const: algorithm_response
      status:
        const: True
      offers:
        type: array
        items:
          $ref: '#/definitions/offer'
  fail:
    type: object
    required:
      - type
      - status
      - message
    properties:
      type:
        const: algorithm_response
        status:
          const: False
        message:
          type: string
  offer:
    type: object
    required:
      - offered_flexibility
      - requested_flexibility
      - start_time
      - end_time
      - building_info
    properties:
      offered_flexibility:
        type: number
      requested_flexibility:
        type: number
      start_time:
        type: string
        format: "date-time"
      end_time:
        type: string
        format: "date-time"
      building_info:
        type: array
        items:
          '$ref': '#/definitions/building_info'
  building_info:
    type: object
    required:
      - building_id
      - start_time
      - end_time
      - flexibility
    properties:
      building_id:
        type: string
      start_time:
        type: string
        format: "date-time"
      end_time:
        type: string
        format: "date-time"
      flexibility:
        type: number
...
