# Generated by Django 4.0.5 on 2022-07-25 10:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_ip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ip',
            new_name='IpCounter',
        ),
    ]
