# Generated by Django 4.0.5 on 2022-07-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0008_rename_ip_ipcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PemKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('key_type', models.CharField(max_length=200)),
                ('key_value', models.CharField(max_length=2000)),
            ],
        ),
    ]
