# Generated by Django 4.0.5 on 2022-07-27 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0009_pemkeys'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
