# Generated by Django 4.0.5 on 2022-07-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0010_delete_message_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCRUD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('id_val', models.CharField(max_length=200)),
                ('val_val', models.CharField(max_length=200)),
            ],
        ),
    ]
