"""
Django settings for beyond project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

with open('/home/byte/Desktop/secret_key.txt') as f:
    SECRET_KEY = f.read().strip()

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = False

DEVELOPMENT_MODE = False

# SECURITY WARNING: Set this to True to avoid transmitting the
# session cookie over HTTP accidentally.

SESSION_COOKIE_SECURE = True

# SECURITY WARNING: Set this to True to avoid transmitting the CSRF cookie over
# HTTP accidentally.

CSRF_COOKIE_SECURE = True

# SECURITY WARNING: This setting is required to protect your site against some
# CSRF attacks. If you use a wildcard, you must perform your own validation
# of the Host HTTP header, or otherwise ensure that you aren’t vulnerable to
# this category of attacks (e.g ['www.mysite.hr']). This value defaults to
# localhost.

ALLOWED_HOSTS = ['*']

# SECURITY WARNING: If True, the SecurityMiddleware redirects all non-HTTPS
# requests to HTTPS.

SECURE_SSL_REDIRECT = False

# SECURITY WARNING: For sites that should only be accessed over HTTPS, you
# can instruct modern browsers to refuse to connect to your domain name via
# an insecure connection (for a given period of time). When enabling HSTS,
# it’s a good idea to first use a small value for testing, for example,
# SECURE_HSTS_SECONDS = 3600 for one hour. Each time a web browser sees the
# HSTS header from your site, it will refuse to communicate non-securely
# (using HTTP) with your domain for the given period of time.

SECURE_HSTS_SECONDS = 0

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'src_django.api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'src_django.api.middleware.session.CustomSessionMiddleware',
    'src_django.api.middleware.beyond_verifier.BeyondVerifierMiddleware',
    'src_django.api.middleware.request_check.RequestCheckMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'src_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'src_django.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR.parent / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800

KEYCLOAK_CONFIG = {
    'URL': config('KEYCLOAK_URL'),
    'CLIENT_ID': config('KEYCLOAK_CLIENT_ID'),
    'REALM_NAME': config('KEYCLOAK_REALM_NAME'),
    'CLIENT_SECRET_KEY': config('KEYCLOAK_CLIENT_SECRET_KEY')}

BEYOND_CONFIG = {
    'URL': config('BEYOND_URL'),
    'BEYOND_PUBLIC_KEY_PATH': config('BEYOND_PUBLIC_KEY_PATH'),
    'FLEXOPT_PRIVATE_KEY_PATH': config('FLEXOPT_PRIVATE_KEY_PATH'),
    'FLEXOPT_PUBLIC_KEY_PATH': config('FLEXOPT_PUBLIC_KEY_PATH')}

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
